name: Monitoreo Web

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar sitio
        run: |
          curl -I https://renzzzzzz-punk.github.io/EcbSoluciones1/
